name: Docker Compose

on:
  push:
    branches: [ "master", "CDCI" ]
  pull_request:
    branches: [ "master", "CDCI" ]

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: tutorial
      POSTGRES_DB: iam
      POSTGRES_PASSWORD: privatepassword
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: privatepassword
    ports:
      - 8000:80

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: docker-compose up --build --detach

      - name: Run tests
        run: |
          # Insérez ici les commandes pour tester votre application

      - name: Stop containers
        run: docker-compose down