# This is a basic workflow to help you get started with Actions

name: Build and Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "CDCI" ]
  pull_request:
    branches: [ "master", "CDCI" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build and Test
    runs-on: ubuntu-latest
      

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: build docker
        run : docker build .\Dockerfile

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: projetsecurecoding:1.0
          file: ./Dockerfile

      # - name: Use Docker
      #   run: docker compose up

      - name: npm ci
        run : npm ci

      - name: build
        run: npm run build

      - name: test
        run: npm run test