name: update and test

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "CDCI" ]
  pull_request:
    branches: [ "master", "CDCI" ]

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env:
      POSTGRES_PASSWORD: tutorial
      POSTGRES_USER: iam
      POSTGRES_DB: privatepassword