# This is a basic workflow to help you get started with Actions

name: Build and Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "CDCI" ]
  pull_request:
    branches: [ "master", "CDCI" ]

  # Allows you to run this workflow manually from the Actions tab

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: tutorial
      POSTGRES_DB: iam
      POSTGRES_PASSWORD: privatepassword
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: privatepassword
    ports:
      - 8000:80
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build and Test
    runs-on: ubuntu-latest
      

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: docker-compose up --build --detach

      - name: build
        run: npm run build

      - name: test
        run: npm run test