# This is a basic workflow to help you get started with Actions

name: Build Docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "CDCI" ]
  pull_request:
    branches: [ "master", "CDCI" ]

env:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: "5432"
  DB_USERNAME: "tutorial"
  DB_PASSWORD: "privatepassword"
  DB_DATABASE: "iam"
  SERVER_PORT: "8080"


jobs:
  build:
    name: build
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: tutorial
          POSTGRES_DB: iam
          POSTGRES_PASSWORD: privatepassword
        ports:
          - 5432:5432

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    